### ISSUE TITLE
ID naming between 1.20.2 and 1.25

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#1455]
After upgrading the WixSharp from 1.20.2 to 1.25.0, the interim wxs files have a different structure, leading to 

> LGHT0091: 
> Duplicate symbol 'Directory:Invantive20Software20BV' found. 
> This typically means that an Id is duplicated. 
> Check to make sure all your identifiers of a given type (File, Component, Feature) are unique.

On 1.20.2, the structure is:

```
    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFilesFolder" Name="ProgramFilesFolder">
        <Directory Id="ProgramFilesFolder.Invantive20Software20BV" Name="Invantive Software BV">
          <Directory Id="INSTALLDIR" Name="Invantive Build Tool 24.1">

            ... components ...

          </Directory>
        </Directory>
      </Directory>

      <Directory Id="ProgramMenuFolder" Name="ProgramMenuFolder">
        <Directory Id="ProgramMenuFolder.Invantive20Software20BV" Name="Invantive Software BV">
          <Directory Id="ProgramMenuFolder.Invantive20Software20BV.Invantive20Build20Tool" Name="Invantive Build Tool">

            ... components ...

          </Directory>

.         ... components ...

        </Directory>
      </Directory>
    </Directory>
```

but on 1.25 the default naming is:

```
    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFilesFolder" Name="ProgramFilesFolder">
        <Directory Id="Invantive20Software20BV" Name="Invantive Software BV">
          <Directory Id="INSTALLDIR" Name="Invantive Build Tool 24.0">

            ... components ...

          </Directory>
        </Directory>
      </Directory>

      <Directory Id="ProgramMenuFolder" Name="ProgramMenuFolder">
        <Directory Id="Invantive20Software20BV" Name="Invantive Software BV">
          <Directory Id="Invantive20Build20Tool" Name="Invantive Build Tool">

            ... components ...

          </Directory>

          ... components ...

        </Directory>
      </Directory>
    </Directory>
```

Please note that on 1.20.2, the Id of the foldres contained a concatenated path of the IDs of all parents, such as `ProgramMenuFolder.Invantive20Software20BV`. This makes it easy to get unique IDs, since a ID must be unique across all directories, but only needs to be checked on the node level.

On 1.25, the same Id `Invantive20Software20BV` is re-used in both trees of ProgramFilesFolder and in ProgramMenuFolder.

Is this an intentional change or a bug?

Besides upgrading WiXSharp, no changes have been made.

The settings on the project include:

```
Compiler.AutoGeneration.LegacyDefaultIdAlgorithm = false;
Compiler.AutoGeneration.CustomIdAlgorithm = projectObject.HashedTargetPathIdAlgorithm;
projectObject.CustomIdAlgorithm = projectObject.HashedTargetPathIdAlgorithm;
```

Might relate to #1244 which was introduced in v1.20.3.

**Comment by monty241** [comment]
Reverting to old algorithm works around the issue, leading again to Id-s for the directory elements with the full path from the root:

```
AutoElements.LegacyDirIdAlgorithm = true;
```

**Comment by monty241** [comment]
When a short is added using:
```
string? name = this.Product.GetMsiProductName(sessionState);
string location = string.Concat("%ProgramMenu%", "\\", this.Product.ManufacturerWithoutDots, "\\", this.Product.ProductNameWithoutMarks);
fileShortCuts.Add(new FileShortcut(new Id(string.Concat("Program", ".", "Menu", ".", name)), name, location));
```
and then the fileShortCuts are included in the project, a component is added below `ProgramFilesFolder`:
```
            <Component Id="Component.File_Invantive.BuildTool.exe_1713595209" Guid="b117615f-ed98-4321-b110-94dae68b8c65">
              <File Id="File_Invantive.BuildTool.exe_1713595209" Source="..\..\solutions\obin\net48\Invantive.BuildTool.exe" Name="Invantive.BuildTool.exe">
                <Shortcut Id="Program.Menu.Invantive Build Tool 24.0" WorkingDirectory="ProjectBase.newMergedDirectoryId" Directory="ProgramMenuFolder.Invantive20Software20BV.Invantive20Build20Tool" Name="Invantive Build Tool 24.0.lnk" />
              </File>

              <RegistryKey Root="HKCU" Key="Software\WixSharp\Used">
                <RegistryValue Value="0" Type="string" KeyPath="yes" />
              </RegistryKey>
            </Component>
```

But It seems that the following directory structure is somehow magically added also due to the shortcut added:

```
      <Directory Id="ProgramMenuFolder" Name="ProgramMenuFolder">
        <Directory Id="ProgramMenuFolder.Invantive20Software20BV" Name="Invantive Software BV">
          <Directory Id="ProgramMenuFolder.Invantive20Software20BV.Invantive20Build20Tool" Name="Invantive Build Tool">

            <Component Id="Component.ProgramMenuFolder.Invantive20Software20BV.Invantive20Build20Tool.EmptyDirectory" Guid="b117615f-ed98-4321-b110-94da7fa66afb">
              <CreateFolder />
              <RemoveFolder Id="ProgramMenuFolder.Invantive20Software20BV.Invantive20Build20Tool" On="uninstall" />

              <RegistryKey Root="HKCU" Key="Software\WixSharp\Used">
                <RegistryValue Value="0" Type="string" KeyPath="yes" />
              </RegistryKey>
            </Component>

          </Directory>

          <Component Id="ProgramMenuFolder.Invantive20Software20BV" Guid="b117615f-ed98-4321-b110-94da0560c40e">
            <CreateFolder />
            <RemoveFolder Id="ProgramMenuFolder.Invantive20Software20BV" On="uninstall" />

            <RegistryKey Root="HKCU" Key="Software\WixSharp\Used">
              <RegistryValue Value="0" Type="string" KeyPath="yes" />
            </RegistryKey>
          </Component>

        </Directory>
      </Directory>
```
This last directory is not created in manual code, but seems somehow injected by WiXSharp.

However, in Compiler.cs near `//insert file owned shortcuts` it seems to be the only code where `Location` is used.

Perhaps the code:

```
Dir locationDir = wProject.FindDir(wShortcut.Location);
```

re-uses the same directory previously created, but starting 1.20.3 causes a duplicate value on Id for directories since the re-used directory is within a different root (`ProgramMenuFolder` instead of `ProgramFilesFolder`).

Perhaps a clone is necessary on the `locationDir` found, while changing the `Id`.

But this is just guessing looking at the code. Reverting to the old behaviour fixes the incident for our use case.

**Comment by oleg-shilo** [comment]
Will have a look.

**Comment by oleg-shilo** [comment]
Hi Guido, I will need your help with reproducing the faulty behaviour.

But first, let's verify a few assumptions.

> This makes it easy to get unique IDs, since a ID must be unique across...

They are still unique. I am not sure about the origin of that XML fragment you shared but if I generate the WXS for the dir structure you specified this is what is generated with the default naming algorithm:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/75976c8c-11bf-4d5c-bf86-9bb9f0293c07)

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/8f1da060-7372-46b4-ab1e-5cb53d388054)

As you can see the algorithm still takes care of the uniqueness of the IDs.

> The settings on the project include...

You do not need to set `CustomIdAlgorithm` as you are setting them to the default algorithm that is used anyway. Setting `LegacyDefaultIdAlgorithm` is enough.  You set `CustomIdAlgorithm` only if you indeed define your own algorithm.

```C#
Compiler.AutoGeneration.LegacyDefaultIdAlgorithm = true;
// Compiler.AutoGeneration.CustomIdAlgorithm = project.HashedTargetPathIdAlgorithm;
// project.CustomIdAlgorithm = project.HashedTargetPathIdAlgorithm;
```

> This last directory is not created in manual code, but seems somehow injected by WiXSharp.

Most likely it was, but I cannot verify it without your code.

Thus I cannot reproduce the problem you described and don't see yet how your codebase got there. Can you share with me something that shows the problem?

This is the code that I used (modified Shortcut sample):
```C#
var project =
    new Project("My Product",
        new Dir(@"%ProgramFiles%\Invantive Software BV\Invantive Build Tool 24.0",
            new File(@"AppFiles\MyApp.exe",
                new FileShortcut("MyApp", "INSTALLDIR"), //INSTALLDIR is the ID of "%ProgramFiles%\My Company\My Product"
                new FileShortcut("MyApp", @"%Desktop%") { IconFile = @"AppFiles\Icon.ico", WorkingDirectory = "Samples", Arguments = "777" }) ),

        new Dir(@"%ProgramMenu%\Invantive Software BV\Invantive Build Tool 24.0",
            new DirectoryShortcut("Samples", "[Samples]"),
            new ExeFileShortcut("Uninstall MyApp", "[System64Folder]msiexec.exe", "/x [ProductCode]")));

project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");
project.UI = WUI.WixUI_ProgressOnly;

project.Platform = Platform.x64;
project.PreserveTempFiles = true;

Compiler.BuildMsi(project);
```
It compiles just fine. The emitted WXS is attached.
[My Product.zip](https://github.com/oleg-shilo/wixsharp/files/14394877/My.Product.zip)

**Comment by monty241** [comment]
My apologies, I never responded to this one!

For searcher: we fixed it by using our own ID's (note that the installdir must be named INSTALLDIR).
